apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: caddy
  labels:
    name: caddy
spec:
  rules:
  
  - host: cafio.co
    http:
      paths: 
      - path: /
        pathType: Prefix
        backend:
          service:
            name: flame-service
            port:
              number: 5005

  - host: media.cafio.co
    http:
      paths:
      - path: /radarr
        pathType: Prefix
        backend:
          service:
            name: radarr-service
            port:
              number: 7878
      - path: /sonarr
        pathType: Prefix
        backend:
          service:
            name: sonarr-service
            port:
              number: 8989
      - path: /sabnzbd
        pathType: Prefix
        backend:
          service:
            name: sabnzbd-service
            port:
              number: 8080

  - host: code.cafio.co
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: code-service
            port:
              number: 8443

  - host: drop.cafio.co
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: pairdrop-service
            port:
              number: 3000