apiVersion: v1
kind: ConfigMap
metadata:
  name: caddyfile
data:
  Caddyfile: |
    # Main site
    cafio.co {
      reverse_proxy flame:5005
    
      file_server /srv
    }
  
    # Plex reverse proxy
    media.cafio.co {
      reverse_proxy https://${HOSTNAME}.lan:32400 {
        transport http {
          tls
          tls_insecure_skip_verify
        }
      }
    
      reverse_proxy /radarr* radarr:7878
      basicauth /radarr/* {
        admin $$2a$$14$$59fq3dJu7BMgI4os7Z11sOqPUjAsZIg9QFytUDIfVR64v8NlA56Ge
      }
    
      reverse_proxy /sonarr* sonarr:8989
      basicauth /sonarr/* {
        admin $$2a$$14$$59fq3dJu7BMgI4os7Z11sOqPUjAsZIg9QFytUDIfVR64v8NlA56Ge
      }
    
      reverse_proxy /sabnzbd* sabnzbd:8080
      basicauth /sabnzbd/* {
        admin $$2a$$14$$59fq3dJu7BMgI4os7Z11sOqPUjAsZIg9QFytUDIfVR64v8NlA56Ge
      }
    }
  
    # VSCode reverse proxy
    code.cafio.co {
      reverse_proxy vscode:8443
      basicauth {
        admin $$2a$$14$$59fq3dJu7BMgI4os7Z11sOqPUjAsZIg9QFytUDIfVR64v8NlA56Ge
      }
    }
  
    # PairDrop reverse proxy
    drop.cafio.co {
      reverse_proxy pairdrop:3000
    }
  
    # Nextcloud reverse proxy
    cloud.cafio.co {
      reverse_proxy nextcloud:8080
    }
  
    # OnlyOffice reverse proxy
    office.cafio.co {
      reverse_proxy nextcloud:8081
    }