apiVersion: apps/v1
kind: Deployment
metadata:
  name: caddy
spec:
  selector:
    matchLabels:
      app: caddy
  template:
    metadata:
      labels:
        app: caddy
    spec:
      containers:
      - name: caddy
        image: caddy:latest
        volumeMounts:
        - name: caddyfile
          mountPath: /etc/caddy/Caddyfile
          subPath: Caddyfile
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
      volumes:
      - name: caddyfile
        configMap:
          name: caddyfile
        ports:
        - containerPort: 80
