apiVersion: apps/v1
kind: Deployment
metadata:
  name: pairdrop
spec:
  selector:
    matchLabels:
      app: pairdrop
  template:
    metadata:
      labels:
        app: pairdrop
    spec:
      containers:
      - name: pairdrop
        image: linuxserver/pairdrop:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
