apiVersion: apps/v1
kind: Deployment
metadata:
  name: code
spec:
  selector:
    matchLabels:
      app: code
  template:
    metadata:
      labels:
        app: code
    spec:
      containers:
      - name: code
        image: linuxserver/code-server:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
